### ISSUE TITLE
How do you add new scenarios when running under docker?

### ISSUE THREAD

**Issue by mikebluestein** [esl/amoc#122]
I have 2 amoc containers running as per this doc:

https://github.com/esl/amoc/blob/master/doc/distributed.md

I added my_scenario.erl under the scenarios folder, but when I attempt to run it with this code my_scenario is not found:

`amoc_dist:do(my_scenario, 100, Settings).`

How do you add new scenarios when running under docker?

**Comment by NelsonVides** [comment]
Hi @mikebluestein 
I think that if running under docker, you might need to inject this `my_scenario` into your container, and compile it within. Have a look at this script, you could use it as `./script.sh 2 my_scenario.erl`, it might help:

```bash
#!/usr/bin/env bash

NODES=${1:-2}
FILE_PATH="${2:-my_scenario.erl}"
FILE=`basename ${FILE_PATH} .erl`

for i in $(seq 1 $NODES); do
    NODE="amoc-${i}"
    echo "cp file ${FILE} from path ${FILE_PATH} to node ${NODE}"
    docker cp ${FILE_PATH} ${NODE}:/home/amoc/amoc/scenarios
    docker exec -it $NODE /home/amoc/amoc/bin/amoc eval "compile:file(\"scenarios/${FILE}\", [{outdir, \"scenarios_ebin\"}, {parse_transform, lager_transform}])."
    docker exec -it $NODE /home/amoc/amoc/bin/amoc eval "code:add_patha(\"scenarios_ebin\"), code:purge(${FILE}), code:load_file(${FILE})."
done
```

So you basically first `docker cp` the file into the container, then tell the Erlang vm to compile it and to load it, and then amoc can find it and use it 🙂

**Comment by DenysGonchar** [comment]
dear @mikebluestein.

According to [rebar.config](https://github.com/esl/amoc/blob/master/rebar.config#L24) it should be compiled and available for execution. But please note that [Dockerfile](https://github.com/esl/amoc/blob/master/Dockerfile#L26) runs "git clean -ffxd" as part of docker image build, so all the non-tracked (by git) files are removed.

anyway, we do not recommend to add scenarios directly to amoc project. the latest release was fully focused on splitting amoc and scenarios, and making amoc just a pure loadtesting framework. 

now you can use amoc as rebar dependency, and have a separate dedicated project with your scenarios. Like it's done for [amoc-arsenal-xmpp](https://github.com/esl/amoc-arsenal-xmpp/).

we highly recommend to go this way.

**Comment by DenysGonchar** [comment]
@mikebluestein please close the issue if you have no other questions.
