### ISSUE TITLE
Update Travis CI OTP version to 18.3

### ISSUE THREAD

**Issue by kklocek** [esl/amoc#37]
Currently we have OTP 17.5 which is a problem with #32  - `httpc` needs higher version because in 17.5 we can't make PATCH request.

**Comment by mentels** [comment]
I think we can do that. Anyone can handle that? @arkgil @bszaf @kklocek

**Comment by michalwski** [comment]
You can also try esl/fusco instead of httpc, but that probably requires more work.

**Comment by mentels** [comment]
Actually, it has already been suggested. I'm for it.

**Comment by kklocek** [comment]
There is a pull request #38 - could @mentels or @michalwski  review it?

**Comment by kklocek** [comment]
There is no need to upgrade to OTP 18.3 because using `fusco` instead of `httpc` solves tests crashing.
