### ISSUE TITLE
copy scenarios to scenarios/

### ISSUE THREAD

**Issue by bartekgorny** [esl/amoc#45]
Every time "make rel" is called, a directory with scenarios is copied to "scenarios/" - which means that you get "_rel/scenarios/scenarios/scenarios" repeated as many times as you have ran "make rel". All this goes to slaves, and seems to result in slaves running an old versions of scenarios.

**Comment by kklocek** [comment]
@bartekgorny Thanks for that! It's somewhat strange, I made a PR which in my case fixes it.

Please test it if you will have more time.

**Comment by studzien** [comment]
Resolved by #46
