### ISSUE TITLE
Measure server response times

### ISSUE THREAD

**Issue by brbrr** [esl/amoc#57]
Hi. I would like to measure how quickly server responses under load.

I was thinking about to measure time between send stanza, and receive stanza (in escalus) But escalus has its own predefined timeouts (3sec for user creation, and 1sec for `get_stanza`) But for this, it would require to tweak escalus code, which is not best solution as for me. Any advice is really appreciated!

P.S. Sorry for kinda off-topic issue

**Comment by michalwski** [comment]
Hi @brbrr 

Response time may not be possible to achieve while sending messages stanzas anyway. What you can measure is Time To Deliver (how long does it take, to deliver a message to other user). We are measuring this in our continuous load testing platform: http://tide.erlang-solutions.com/public
You can look at scenario file: https://github.com/esl/amoc/blob/master/scenarios/mongoose_simple_with_metrics.erl to see how we compute such metric.

**Comment by DenysGonchar** [comment]
no actions for almost 3 years, closing this one.
