### ISSUE TITLE
Dependency hell will occur when escalus will be upgraded to newest version

### ISSUE THREAD

**Issue by bszaf** [esl/amoc#61]
```
    +------------+
    |            |
    |    AMOC    +------------+
    |            |            |
    ++-----------+            |
     |                        |
     |                        |
     |                        v
     v                 +------+--------+      +-----------+
+----+------+          |               |      |           |
|           |          |   escalus     +----->+  gun      |
|  Cowboy   |          |   master      |      |           |
|   v1.0    |          |   g7081f90    |      +---+-------+
|           |          +---------------+          |
+----+------+                                     |
     |                                            |
     |                                            |
     |                                            |
     v                                            |
+----+-------+        +-----------------+         |
|            |        |                 |         |
|  Cowlib    |        |    Cowlib       +<--------+
|   v1.0     |        |    >=v1.2       |
|            |        |                 |
+------------+        +-----------------+

```
> Fig 1. Dependecies in Amoc after escalus upgrade

Currently we are using Cowboy 1.0 for HTTP API for `amoc`. It depends on legacy version of `cowlib`. However `escalus` is using `gun` for websocket handing, which depends on `cowlib`. A far as I inspected it, it should work with `cowlib 1.2`, however it specifies in `rebar.config`, that it depends on `master` branch of cowlib.

What we can do:
 - rewrite AMOC HTTP API to cowboy 2.0

**Comment by arcusfelis** [comment]
We can split AMOC into HTTP interface node and test node, communicating over erlang distribution with each other.

**Comment by michalwski** [comment]
+1 from for rewriting Amoc's HTTP API to work with cowboy 2.0

**Comment by mentels** [comment]
Currently for MT we use hack-patched [Amoc version](https://github.com/esl/amoc/tree/temporary_escalus_update). It requires to pass `{socket_opts, Opts}` to the `UserSpec` as used in the [MT Load Test scenario](https://github.com/esl/amoc/tree/temporary_escalus_update).

**Comment by mentels** [comment]
+1 for rewriting Amoc to use cowboy 2.0 (or 2.2).
