### ISSUE TITLE
Amoc docker container is broken

### ISSUE THREAD

**Issue by bszaf** [esl/amoc#64]
After #62 or #63 was merged, docker container became unusable. Basically amoc fails to start.

logs:
---

```
Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k
root@280101be614f:/home/amoc/amoc#
```

**Comment by ludwikbukowskiolx** [comment]
When you build amoc from sources with `make rel` it doesn't include libraries (e.g escalus) in release. Generally whole amoc is unusable now I think

**Comment by michalwski** [comment]
@bszaf is this issue still valid?

**Comment by DenysGonchar** [comment]
not relevant any more
